NAME = libft.a
AR = ar
SRCS_b = ft_lstadd_back.c  ft_lstadd_front.c  ft_lstclear.c  ft_lstdelone.c  ft_lstiter.c  ft_lstlast.c  ft_lstmap.c  ft_lstnew.c  ft_lstsize.c

SRCS = ft_atoi.c     ft_isdigit.c       ft_memchr.c      ft_putendl_fd.c  ft_striteri.c  ft_strncmp.c  ft_toupper.c \
       ft_bzero.c    ft_isprint.c       ft_memcmp.c      ft_putnbr_fd.c   ft_strjoin.c   ft_strnstr.c \
       ft_calloc.c   ft_itoa.c          ft_memcpy.c      ft_putstr_fd.c   ft_strlcat.c   ft_strrchr.c \
       ft_isalnum.c  ft_memmove.c       ft_split.c       ft_strlcpy.c     ft_strtrim.c \
       ft_isalpha.c  ft_memset.c        ft_strchr.c      ft_strlen.c      ft_substr.c \
       ft_isascii.c  ft_putchar_fd.c    ft_strdup.c      ft_strmapi.c     ft_tolower.c

OBJS = $(SRCS:.c=.o)
OBJS_b = $(SRCS_b:.c=.o)
CC = clang
CFLAGS = -Wall -Wextra -Werror 

token: $(NAME)

$(NAME): $(OBJS)
	$(AR) -rc $(NAME) $(OBJS)
	ranlib $(NAME)

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(OBJS) $(OBJS_b)

fclean: clean
	rm -f $(NAME)

re: fclean token

bonus: $(OBJS) $(OBJS_b) 
	$(AR) -rc $(NAME) $^
	@touch bonus

	
